-- RiotAccount: 솔로/자유랭크 시즌 누적 승패 + 자유랭크 현재값 저장
ALTER TABLE "riot_accounts"
  ADD COLUMN "soloWins" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "soloLosses" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "flexTier" TEXT NOT NULL DEFAULT 'UNRANKED',
  ADD COLUMN "flexRank" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "flexLp" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "flexWins" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "flexLosses" INTEGER NOT NULL DEFAULT 0;
