"use client";

import { useState } from "react";
import { Check, Play, Trophy } from "lucide-react";

const teams = ["NEXUS", "BLUE", "NOVA", "RUSH", "ORBIT", "TIGER"];

export default function PubgScrimFlowPreview() {
  const [mode, setMode] = useState<"KILL_MATCH" | "BATTLE_ROYALE">("BATTLE_ROYALE");
  const [stage, setStage] = useState(0);
  const labels = mode === "KILL_MATCH" ? ["설정", "팀장 준비", "시간제 경기", "결과 검토", "최종 결과"] : ["설정", "라운드 시작", "경기 진행", "누적 순위", "최종 결과"];
  return <main className="min-h-screen bg-bg-primary px-5 py-10 text-text-primary md:px-10"><div className="mx-auto max-w-6xl space-y-7"><header><p className="text-sm font-semibold text-accent-primary">NEXUS · PUBG FLOW PREVIEW</p><h1 className="mt-2 text-3xl font-black">팀 편성 후 화면 흐름</h1><p className="mt-2 text-sm text-text-secondary">실제 방 데이터 없이 두 모드의 화면을 단계별로 확인합니다.</p></header><div className="flex gap-2">{(["KILL_MATCH","BATTLE_ROYALE"] as const).map(value => <button key={value} onClick={() => { setMode(value); setStage(0); }} className={mode === value ? "rounded-lg bg-accent-primary px-4 py-2 text-sm font-bold text-white" : "rounded-lg bg-bg-secondary px-4 py-2 text-sm font-bold text-text-secondary"}>{value === "KILL_MATCH" ? "킬내기" : "배틀로얄"}</button>)}</div><div className="rounded-2xl border border-bg-tertiary bg-bg-secondary p-4"><div className="flex items-center gap-2 overflow-x-auto">{labels.map((label,index) => <button key={label} onClick={() => setStage(index)} className="flex min-w-max flex-1 items-center gap-2 text-left"><span className={index <= stage ? "flex h-8 w-8 items-center justify-center rounded-full bg-accent-primary text-xs font-bold text-white" : "flex h-8 w-8 items-center justify-center rounded-full border border-bg-elevated text-xs text-text-tertiary"}>{index < stage ? <Check className="h-4 w-4" /> : index + 1}</span><span className={index === stage ? "text-sm font-bold" : "text-sm text-text-tertiary"}>{label}</span>{index < labels.length-1 && <span className="mx-1 h-px flex-1 bg-bg-elevated" />}</button>)}</div></div><section className="rounded-2xl border border-bg-tertiary bg-bg-secondary p-6 md:p-8">{stage === 0 && <Setup mode={mode} next={() => setStage(1)} />}{stage === 1 && <Ready mode={mode} next={() => setStage(2)} />}{stage === 2 && <Match mode={mode} next={() => setStage(3)} />}{stage === 3 && <Ranking mode={mode} next={() => setStage(4)} />}{stage === 4 && <Final mode={mode} />}</section></div></main>;
}

function Setup({mode,next}:{mode:string;next:()=>void}){return <div className="mx-auto max-w-2xl space-y-6"><div><p className="text-sm font-semibold text-accent-primary">{mode==="KILL_MATCH"?"킬내기":"배틀로얄 스크림"}</p><h2 className="mt-2 text-2xl font-bold">스크림 설정</h2><p className="mt-2 text-sm text-text-secondary">{mode==="KILL_MATCH"?"제한시간 동안 여러 경기를 자동 집계합니다.":"정해진 라운드 수를 순서대로 진행합니다."}</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-bg-tertiary bg-bg-primary p-4"><p className="text-xs text-text-tertiary">{mode==="KILL_MATCH"?"진행시간":"라운드 수"}</p><p className="mt-2 text-xl font-bold">{mode==="KILL_MATCH"?"60분":"3라운드"}</p></div><div className="rounded-xl border border-accent-primary/50 bg-accent-primary/10 p-4"><p className="text-xs text-text-tertiary">포인트 규칙</p><p className="mt-2 text-xl font-bold">표준 규칙</p></div></div><button onClick={next} className="rounded-lg bg-accent-primary px-5 py-3 text-sm font-bold text-white">스크림 시작</button></div>}
function Ready({mode,next}:{mode:string;next:()=>void}){return <div className="mx-auto max-w-2xl space-y-6"><p className="text-sm font-semibold text-accent-primary">{mode==="KILL_MATCH"?"킬내기 시작 전":"1라운드 시작 전"}</p><h2 className="text-2xl font-bold">{mode==="KILL_MATCH"?"팀장 준비":"팀 편성 완료"}</h2><p className="text-sm text-text-secondary">{mode==="KILL_MATCH"?"모든 팀장이 준비하면 제한시간이 시작됩니다.":"방장이 다음 라운드를 시작합니다."}</p>{mode==="KILL_MATCH"&&<div className="grid gap-3 sm:grid-cols-2">{teams.slice(0,4).map((team,i)=><div key={team} className="flex justify-between rounded-xl border border-bg-tertiary p-4"><span className="font-semibold">{team} 팀장</span><span className="text-accent-success">{i<3?"준비":"대기"}</span></div>)}</div>}<button onClick={next} className="rounded-lg bg-accent-primary px-5 py-3 text-sm font-bold text-white">{mode==="KILL_MATCH"?"전원 준비 완료":"1라운드 시작"}</button></div>}
function Match({mode,next}:{mode:string;next:()=>void}){return <div className="space-y-6"><div className="flex justify-between"><div><p className="text-sm font-semibold text-accent-primary">{mode==="KILL_MATCH"?"시간제 경기 진행":"1라운드 진행"}</p><h2 className="mt-2 text-2xl font-bold">게임 결과를 기다리는 중</h2><p className="mt-2 text-sm text-text-secondary">{mode==="KILL_MATCH"?"커스텀 매치 결과를 자동 수집합니다.":"경기 종료 후 결과를 입력합니다."}</p></div><Play className="h-8 w-8 text-accent-primary" /></div><div className="grid gap-3 md:grid-cols-3">{teams.slice(0,3).map((team,i)=><div key={team} className="rounded-xl border border-bg-tertiary bg-bg-primary p-4"><p className="font-bold">{team}</p><p className="mt-3 text-2xl font-black">{12-i*3}킬</p></div>)}</div><button onClick={next} className="rounded-lg bg-accent-primary px-5 py-3 text-sm font-bold text-white">결과 확인</button></div>}
const battleRoyaleStats = [
  { team: "NEXUS", points: 96, kills: 34, deaths: 7, players: [["mango", 12, 2], ["sora", 9, 1], ["raven", 8, 3], ["june", 5, 1]] },
  { team: "BLUE", points: 85, kills: 29, deaths: 11, players: [["taro", 10, 3], ["mint", 8, 2], ["zero", 7, 4], ["noah", 4, 2]] },
  { team: "NOVA", points: 77, kills: 25, deaths: 13, players: [["luna", 9, 3], ["kiri", 7, 2], ["dawn", 6, 5], ["bean", 3, 3]] },
  { team: "RUSH", points: 68, kills: 22, deaths: 16, players: [["rushA", 8, 4], ["rushB", 6, 3], ["rushC", 5, 5], ["rushD", 3, 4]] },
  { team: "ORBIT", points: 59, kills: 18, deaths: 19, players: [["orbit1", 7, 4], ["orbit2", 5, 5], ["orbit3", 4, 6], ["orbit4", 2, 4]] },
  { team: "TIGER", points: 47, kills: 14, deaths: 22, players: [["tiger1", 5, 6], ["tiger2", 4, 5], ["tiger3", 3, 6], ["tiger4", 2, 5]] },
] as const;

const killMatchStats = [
  { team: "NEXUS", win: 30, kill: 34, penalty: 2, total: 62 },
  { team: "BLUE", win: 22, kill: 29, penalty: 3, total: 48 },
  { team: "NOVA", win: 18, kill: 25, penalty: 4, total: 39 },
  { team: "RUSH", win: 12, kill: 22, penalty: 5, total: 29 },
] as const;

function Ranking({mode,next}:{mode:string;next:()=>void}){
  const [expanded, setExpanded] = useState<string | null>(null);
  if (mode === "KILL_MATCH") return <div className="space-y-6"><div><p className="text-sm font-semibold text-accent-primary">킬내기 결과 시트</p><h2 className="mt-2 text-2xl font-bold">승점 + 킬점수로 보는 누적 결과</h2><p className="mt-2 text-sm text-text-secondary">공개 대회 시트처럼 팀별 승점, 킬점수, 총점을 고정해 비교합니다.</p></div><div className="overflow-x-auto rounded-xl border border-bg-tertiary"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-bg-primary text-xs text-text-tertiary"><tr><th className="px-4 py-3">순위</th><th className="px-4 py-3">팀</th><th className="px-4 py-3 text-right">승점</th><th className="px-4 py-3 text-right">킬점수</th><th className="px-4 py-3 text-right">사망 감점</th><th className="px-4 py-3 text-right">총점</th></tr></thead><tbody>{killMatchStats.map((row,i)=><tr key={row.team} className="border-t border-bg-tertiary bg-bg-secondary"><td className="px-4 py-3 font-black">{i+1}</td><td className="px-4 py-3 font-bold">{row.team}</td><td className="px-4 py-3 text-right">{row.win}</td><td className="px-4 py-3 text-right text-accent-primary">{row.kill}</td><td className="px-4 py-3 text-right text-accent-danger">-{row.penalty}</td><td className="px-4 py-3 text-right text-lg font-black">{row.total}</td></tr>)}</tbody></table></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-bg-tertiary bg-bg-primary p-4"><p className="text-xs text-text-tertiary">팀 K/D 기록</p><p className="mt-2 text-sm font-semibold">NEXUS <span className="text-accent-primary">34 / 7</span></p><p className="mt-1 text-xs text-text-secondary">킬내기는 팀 총점이 우선이고, 상세 K/D는 보조 지표로 확인합니다.</p></div><div className="rounded-xl border border-bg-tertiary bg-bg-primary p-4"><p className="text-xs text-text-tertiary">집계 상태</p><p className="mt-2 text-sm font-semibold text-accent-success">모든 팀 결과 수집 완료</p><p className="mt-1 text-xs text-text-secondary">관리자가 제출한 경기 기록을 확정하면 최종 결과로 이동합니다.</p></div></div><button onClick={next} className="rounded-lg bg-accent-primary px-5 py-3 text-sm font-bold text-white">최종 확정</button></div>;
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-accent-primary">누적 순위 · 3라운드</p><h2 className="mt-2 text-2xl font-bold">팀별 총점과 선수별 K/D</h2><p className="mt-2 text-sm text-text-secondary">팀이 많아도 요약 행만 먼저 보여주고, 필요한 팀을 펼쳐 선수 기록을 확인합니다.</p></div><div className="overflow-x-auto rounded-xl border border-bg-tertiary"><div className="min-w-[760px]"><div className="grid grid-cols-[56px_1fr_90px_90px_90px_90px] gap-3 bg-bg-primary px-4 py-3 text-xs text-text-tertiary"><span>순위</span><span>팀</span><span className="text-right">총점</span><span className="text-right">총 킬</span><span className="text-right">총 데스</span><span className="text-right">팀 K/D</span></div>{battleRoyaleStats.map((row,i)=><div key={row.team} className="border-t border-bg-tertiary"><button onClick={() => setExpanded(expanded === row.team ? null : row.team)} aria-expanded={expanded === row.team} className="grid w-full grid-cols-[56px_1fr_90px_90px_90px_90px] gap-3 bg-bg-secondary px-4 py-3 text-left text-sm transition hover:bg-bg-primary"><span className="font-black">{i+1}<span className={i<2 ? "ml-2 text-accent-success" : "ml-2 text-text-tertiary"}>{i<2 ? "▲" : "–"}</span></span><span className="font-bold">{row.team}</span><span className="text-right text-lg font-black">{row.points}</span><span className="text-right text-accent-primary">{row.kills}</span><span className="text-right text-text-secondary">{row.deaths}</span><span className="text-right font-semibold">{(row.kills / row.deaths).toFixed(2)}</span></button>{expanded === row.team && <div className="grid gap-2 border-t border-bg-tertiary bg-bg-primary p-4 sm:grid-cols-2 lg:grid-cols-4">{row.players.map(([name,kills,deaths])=><div key={name} className="rounded-lg border border-bg-tertiary bg-bg-secondary p-3"><div className="flex items-center justify-between"><span className="font-semibold">{name}</span><span className="text-xs text-text-tertiary">K/D</span></div><p className="mt-2 text-lg font-black">{kills} <span className="text-text-tertiary">/</span> {deaths}</p><p className="mt-1 text-xs text-text-secondary">KDA 보조값: A 미수집</p></div>)}</div>}</div>)}</div></div><p className="text-xs text-text-tertiary">현재 PUBG 수집 데이터는 킬·데스 기준입니다. 어시스트 데이터가 연결되면 선수 카드의 KDA를 K/D/A로 확장합니다.</p><button onClick={next} className="rounded-lg bg-accent-primary px-5 py-3 text-sm font-bold text-white">최종 확정</button></div>;
}


function Final({mode}:{mode:string}){return <div className="space-y-6 text-center"><Trophy className="mx-auto h-12 w-12 text-accent-warning" /><p className="text-sm font-semibold text-accent-primary">{mode==="KILL_MATCH"?"킬내기 최종 결과":"배틀로얄 최종 결과"}</p><h2 className="text-3xl font-black">NEXUS 우승</h2><div className="grid gap-3 md:grid-cols-3">{["NEXUS","BLUE","NOVA"].map((team,i)=><div key={team} className="rounded-xl border border-accent-warning/30 bg-accent-warning/5 p-5"><p className="text-xs text-text-tertiary">{i+1}위</p><p className="mt-2 text-lg font-black">{team}</p><p className="mt-1 text-sm text-text-secondary">{120-i*17}점</p></div>)}</div></div>}
