"use client";

import { useState } from "react";
import { Check, Play, Trophy } from "lucide-react";

const teams = ["NEXUS", "BLUE", "NOVA", "RUSH", "ORBIT", "TIGER"];

export default function PubgScrimFlowPreview() {
  const [mode, setMode] = useState<"KILL_MATCH" | "BATTLE_ROYALE">("BATTLE_ROYALE");
  const [stage, setStage] = useState(0);
  const labels = mode === "KILL_MATCH" ? ["설정", "팀장 준비", "시간제 경기", "결과 검토", "최종 결과"] : ["설정", "라운드 시작", "경기 진행", "누적 순위", "최종 결과"];
  return <main className="min-h-screen bg-bg-primary px-5 py-10 text-text-primary md:px-10"><div className="mx-auto max-w-6xl space-y-7"><header><p className="text-sm font-semibold text-accent-primary">NEXUS · PUBG FLOW PREVIEW</p><h1 className="mt-2 text-3xl font-black">팀 편성 후 화면 흐름</h1><p className="mt-2 text-sm text-text-secondary">실제 방 데이터 없이 두 모드의 화면을 단계별로 확인합니다.</p></header><div className="flex gap-2">{(["KILL_MATCH","BATTLE_ROYALE"] as const).map(value => <button key={value} onClick={() => { setMode(value); setStage(0); }} className={mode === value ? "rounded-lg bg-accent-primary px-4 py-2 text-sm font-bold text-white" : "rounded-lg bg-bg-secondary px-4 py-2 text-sm font-bold text-text-secondary"}>{value === "KILL_MATCH" ? "킬내기" : "배틀로얄"}</button>)}</div><div className="rounded-2xl border border-bg-tertiary bg-bg-secondary p-4"><div className="flex items-center gap-2 overflow-x-auto">{labels.map((label,index) => <button key={label} onClick={() => setStage(index)} className="flex min-w-max flex-1 items-center gap-2 text-left"><span className={index <= stage ? "flex h-8 w-8 items-center justify-center rounded-full bg-accent-primary text-xs font-bold text-white" : "flex h-8 w-8 items-center justify-center rounded-full border border-bg-elevated text-xs text-text-tertiary"}>{index < stage ? <Check className="h-4 w-4" /> : index + 1}</span><span className={index === stage ? "text-sm font-bold" : "text-sm text-text-tertiary"}>{label}</span>{index < labels.length-1 && <span className="mx-1 h-px flex-1 bg-bg-elevated" />}</button>)}</div></div><section className="rounded-2xl border border-bg-tertiary bg-bg-secondary p-6 md:p-8">{stage === 0 && <Setup mode={mode} next={() => setStage(1)} />}{stage === 1 && <Ready mode={mode} next={() => setStage(2)} />}{stage === 2 && <Match mode={mode} next={() => setStage(3)} />}{stage === 3 && <Ranking next={() => setStage(4)} />}{stage === 4 && <Final mode={mode} />}</section></div></main>;
}

function Setup({mode,next}:{mode:string;next:()=>void}){return <div className="mx-auto max-w-2xl space-y-6"><div><p className="text-sm font-semibold text-accent-primary">{mode==="KILL_MATCH"?"킬내기":"배틀로얄 스크림"}</p><h2 className="mt-2 text-2xl font-bold">스크림 설정</h2><p className="mt-2 text-sm text-text-secondary">{mode==="KILL_MATCH"?"제한시간 동안 여러 경기를 자동 집계합니다.":"정해진 라운드 수를 순서대로 진행합니다."}</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-bg-tertiary bg-bg-primary p-4"><p className="text-xs text-text-tertiary">{mode==="KILL_MATCH"?"진행시간":"라운드 수"}</p><p className="mt-2 text-xl font-bold">{mode==="KILL_MATCH"?"60분":"3라운드"}</p></div><div className="rounded-xl border border-accent-primary/50 bg-accent-primary/10 p-4"><p className="text-xs text-text-tertiary">포인트 규칙</p><p className="mt-2 text-xl font-bold">표준 규칙</p></div></div><button onClick={next} className="rounded-lg bg-accent-primary px-5 py-3 text-sm font-bold text-white">스크림 시작</button></div>}
function Ready({mode,next}:{mode:string;next:()=>void}){return <div className="mx-auto max-w-2xl space-y-6"><p className="text-sm font-semibold text-accent-primary">{mode==="KILL_MATCH"?"킬내기 시작 전":"1라운드 시작 전"}</p><h2 className="text-2xl font-bold">{mode==="KILL_MATCH"?"팀장 준비":"팀 편성 완료"}</h2><p className="text-sm text-text-secondary">{mode==="KILL_MATCH"?"모든 팀장이 준비하면 제한시간이 시작됩니다.":"방장이 다음 라운드를 시작합니다."}</p>{mode==="KILL_MATCH"&&<div className="grid gap-3 sm:grid-cols-2">{teams.slice(0,4).map((team,i)=><div key={team} className="flex justify-between rounded-xl border border-bg-tertiary p-4"><span className="font-semibold">{team} 팀장</span><span className="text-accent-success">{i<3?"준비":"대기"}</span></div>)}</div>}<button onClick={next} className="rounded-lg bg-accent-primary px-5 py-3 text-sm font-bold text-white">{mode==="KILL_MATCH"?"전원 준비 완료":"1라운드 시작"}</button></div>}
function Match({mode,next}:{mode:string;next:()=>void}){return <div className="space-y-6"><div className="flex justify-between"><div><p className="text-sm font-semibold text-accent-primary">{mode==="KILL_MATCH"?"시간제 경기 진행":"1라운드 진행"}</p><h2 className="mt-2 text-2xl font-bold">게임 결과를 기다리는 중</h2><p className="mt-2 text-sm text-text-secondary">{mode==="KILL_MATCH"?"커스텀 매치 결과를 자동 수집합니다.":"경기 종료 후 결과를 입력합니다."}</p></div><Play className="h-8 w-8 text-accent-primary" /></div><div className="grid gap-3 md:grid-cols-3">{teams.slice(0,3).map((team,i)=><div key={team} className="rounded-xl border border-bg-tertiary bg-bg-primary p-4"><p className="font-bold">{team}</p><p className="mt-3 text-2xl font-black">{12-i*3}킬</p></div>)}</div><button onClick={next} className="rounded-lg bg-accent-primary px-5 py-3 text-sm font-bold text-white">결과 확인</button></div>}
function Ranking({next}:{next:()=>void}){return <div className="space-y-6"><p className="text-sm font-semibold text-accent-primary">누적 순위</p><h2 className="text-2xl font-bold">라운드 결과와 순위 변동</h2><div className="space-y-2">{teams.map((team,i)=><div key={team} className="flex gap-3 rounded-xl border border-bg-tertiary bg-bg-primary p-3"><span className="w-7 font-black">{i+1}</span><span className="flex-1 font-semibold">{team}</span><span className="text-accent-success">{i<2?"▲":"–"}</span><b>{96-i*11}점</b></div>)}</div><button onClick={next} className="rounded-lg bg-accent-primary px-5 py-3 text-sm font-bold text-white">최종 확정</button></div>}
function Final({mode}:{mode:string}){return <div className="space-y-6 text-center"><Trophy className="mx-auto h-12 w-12 text-accent-warning" /><p className="text-sm font-semibold text-accent-primary">{mode==="KILL_MATCH"?"킬내기 최종 결과":"배틀로얄 최종 결과"}</p><h2 className="text-3xl font-black">NEXUS 우승</h2><div className="grid gap-3 md:grid-cols-3">{["NEXUS","BLUE","NOVA"].map((team,i)=><div key={team} className="rounded-xl border border-accent-warning/30 bg-accent-warning/5 p-5"><p className="text-xs text-text-tertiary">{i+1}위</p><p className="mt-2 text-lg font-black">{team}</p><p className="mt-1 text-sm text-text-secondary">{120-i*17}점</p></div>)}</div></div>}
