-- 관리자 스크림 조치 감사 로그용 액션
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'SCRIM_ROUND_RESET';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'SCRIM_COLLECT_RETRY';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'SCRIM_CANCEL';
